package image

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/pocketbase/pocketbase/tools/filesystem"

	"mrtang-pim/internal/config"
)

type Request struct {
	SupplierCode string
	SKU          string
	Title        string
	SourceURL    string
}

type Result struct {
	File   *filesystem.File
	Source string
}

type Processor interface {
	Process(ctx context.Context, req Request) (Result, error)
}

func NewProcessor(cfg config.ImageConfig) Processor {
	if strings.EqualFold(cfg.Processor, "webhook") && strings.TrimSpace(cfg.WebhookURL) != "" {
		return &WebhookProcessor{
			client: &http.Client{Timeout: cfg.Timeout},
			url:    cfg.WebhookURL,
			token:  cfg.WebhookToken,
		}
	}

	return &MockProcessor{}
}

type MockProcessor struct{}

func (p *MockProcessor) Process(_ context.Context, req Request) (Result, error) {
	filename := safeFilename(req.SupplierCode + "-" + req.SKU + ".svg")
	content := fmt.Sprintf(
		`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1200">
<rect width="100%%" height="100%%" fill="#f5efe3"/>
<rect x="48" y="48" width="1104" height="1104" rx="36" fill="#fffaf2" stroke="#3e3128" stroke-width="8"/>
<text x="88" y="180" font-size="56" font-family="Arial, sans-serif" fill="#3e3128">Supplier: %s</text>
<text x="88" y="280" font-size="48" font-family="Arial, sans-serif" fill="#7a6555">SKU: %s</text>
<text x="88" y="400" font-size="62" font-family="Arial, sans-serif" fill="#1f1f1f">%s</text>
<text x="88" y="1090" font-size="32" font-family="Arial, sans-serif" fill="#7a6555">Mock AI processed image generated by mrtang-pim</text>
</svg>`,
		escapeXML(req.SupplierCode),
		escapeXML(req.SKU),
		escapeXML(req.Title),
	)

	file, err := filesystem.NewFileFromBytes([]byte(content), filename)
	if err != nil {
		return Result{}, err
	}

	return Result{
		File:   file,
		Source: "mock",
	}, nil
}

type WebhookProcessor struct {
	client *http.Client
	url    string
	token  string
}

type webhookResponse struct {
	OutputURL  string `json:"output_url"`
	Base64Data string `json:"base64_data"`
	Filename   string `json:"filename"`
}

func (p *WebhookProcessor) Process(ctx context.Context, req Request) (Result, error) {
	payload, err := json.Marshal(req)
	if err != nil {
		return Result{}, err
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, p.url, bytes.NewReader(payload))
	if err != nil {
		return Result{}, err
	}

	httpReq.Header.Set("Content-Type", "application/json")
	if p.token != "" {
		httpReq.Header.Set("Authorization", "Bearer "+p.token)
	}

	resp, err := p.client.Do(httpReq)
	if err != nil {
		return Result{}, err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= http.StatusBadRequest {
		return Result{}, fmt.Errorf("image webhook returned status %d", resp.StatusCode)
	}

	var decoded webhookResponse
	if err := json.NewDecoder(resp.Body).Decode(&decoded); err != nil {
		return Result{}, err
	}

	if strings.TrimSpace(decoded.OutputURL) != "" {
		file, err := filesystem.NewFileFromURL(ctx, decoded.OutputURL)
		if err != nil {
			return Result{}, err
		}

		return Result{
			File:   file,
			Source: decoded.OutputURL,
		}, nil
	}

	if strings.TrimSpace(decoded.Base64Data) == "" {
		return Result{}, fmt.Errorf("image webhook returned empty payload")
	}

	data, err := base64.StdEncoding.DecodeString(decoded.Base64Data)
	if err != nil {
		return Result{}, err
	}

	filename := decoded.Filename
	if strings.TrimSpace(filename) == "" {
		filename = safeFilename(req.SupplierCode + "-" + req.SKU + "-" + time.Now().Format("20060102150405") + ".png")
	}

	file, err := filesystem.NewFileFromBytes(data, filename)
	if err != nil {
		return Result{}, err
	}

	return Result{
		File:   file,
		Source: "webhook",
	}, nil
}

func safeFilename(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "processed-image.svg"
	}

	replacer := strings.NewReplacer(" ", "-", "/", "-", "\\", "-", ":", "-", "*", "-", "?", "-", "\"", "", "<", "", ">", "", "|", "")
	return replacer.Replace(value)
}

func escapeXML(value string) string {
	replacer := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;", "'", "&apos;")
	return replacer.Replace(value)
}
